//
// Generated file, do not edit! Created by nedtool 5.6 from Eth_pck.msg.
//

#ifndef __ETH_PCK_M_H
#define __ETH_PCK_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>Eth_pck.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet Eth_pck
 * {
 *     //char source_mac[6];
 *     //char dest_mac[6];
 *     string source_mac;
 *     string dest_mac;
 *     int TTL;
 *     short Ethertype;             //0: enthernet   1:arp
 * }
 * </pre>
 */
class Eth_pck : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::opp_string source_mac;
    ::omnetpp::opp_string dest_mac;
    int TTL;
    short Ethertype;

  private:
    void copy(const Eth_pck& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Eth_pck&);

  public:
    Eth_pck(const char *name=nullptr, short kind=0);
    Eth_pck(const Eth_pck& other);
    virtual ~Eth_pck();
    Eth_pck& operator=(const Eth_pck& other);
    virtual Eth_pck *dup() const override {return new Eth_pck(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getSource_mac() const;
    virtual void setSource_mac(const char * source_mac);
    virtual const char * getDest_mac() const;
    virtual void setDest_mac(const char * dest_mac);
    virtual int getTTL() const;
    virtual void setTTL(int TTL);
    virtual short getEthertype() const;
    virtual void setEthertype(short Ethertype);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Eth_pck& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Eth_pck& obj) {obj.parsimUnpack(b);}


#endif // ifndef __ETH_PCK_M_H

